spring:
  redis:
    host: 10.170.162.0
    port: 6379
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
          - id: changgou_goods_route
            uri: lb://goods
            predicates:
              - Path=/api/goods/**
            filters:
            - StripPrefix=1
              # RequestRateLimiter : 局部限流过滤器
            - name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的facatory
              args:
                # 用户身份唯一识别标识符，通过SPEL表达式指定使用哪一个KeyResolver
                key-resolver: "#{@ipKeyResolver}"
                # 每秒钟只允许1个请求,该数量范围内的请求不会被丢弃。这是令牌桶填充的速率
                redis-rate-limiter.replenishRate: 1
                # 允许并发有1个请求，此值设置为0将阻止所有请求
                redis-rate-limiter.burstCapacity: 1
          #用户微服务
          - id: changgou_user_route
            uri: lb://user
            predicates:
              - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
            filters:
              - StripPrefix=1
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true

          #      routes:
          # 唯一标识符
          #        - id: changgou_goods_route
          # 用户请求需要路由到该服务[指定要路由的服务]
          #          uri: http://localhost:18081
          # lb:使用LoadBalancerClient实现负载均衡，后面goods是微服务的名称[主要用于集群环境]
          #          uri:lb://goods
          # 路由断言，路由规则配置
          #          predicates:
          # 用户请求的域名规则配置，所有以cloud.itheima.com的请求都将被路由到http://localhost:18081指定的微服务中去
          # - Host=cloud.itheima.com**
          #           # 所有以/brand开始的请求，都路由到http://localhost:18081微服务
          #           - Path=/brand/**
          # 所有以/brand开始的请求，都路由到http://localhost:18081微服务
          #          - Path=/**
          # 所有以/api/brand的请求，都被路由到http://localhost:18081微服务
          # 希望该路径由微服务网关自动给我添加上/api前缀，每次请求真实微服务网关的时候，需要使用微服务网关将/api去掉
          #          filter:
          # 将请求路径中的第一个路径去掉，请求路径以/区分，一个/代表一个路径
          #          - StripPrefix=1
          # 用户请求/** --> /brand/**,并将该请求路由到http://localhost:18081中
#          - PrefixPath=/brand